#!/bin/bash

echo -n > ./log/log.txt

exec 1>./log/log.txt
exec 2>./log/log.txt

echo "Welcome to the vehicle monitoring system of PUP vehicles"

echo "Cleaning cache files..."

echo -n > ./data/gps_data.txt
echo -n > ./data/rpm_data.txt
echo -n > ./data/temp_data.txt

echo "Cache files cleaned..."

vid=demo    # Specify the vehicle ID here. Each vehicle should have a unique ID

sudo pigpiod 2> /dev/null
echo -n > ./data/pid.txt

python3 pupgps.py $vid &
echo $! >> ./data/pid.txt
echo $!  # For testing purpose
echo "GPS sensor started successfully"

python3 temp.py $vid &
echo $! >> ./data/pid.txt
echo $!  # For testing purpose
echo "Temperature sensor started successfully"

python3 read_RPM.py $vid &
echo $! >> ./data/pid.txt
echo $!  # For testing purpose
echo "RPM sensor started successfully"

echo "All sensors started successfully! The monitoring has started..."

while true; do
    # Upload GPS, RPM, and temperature data in a certain time interval
    sleep 10

    scp -i ~/.ssh/bitnami ./data/gps_data.txt bitnami@35.224.122.42:/opt/bitnami/apache/htdocs/data
    scp -i ~/.ssh/bitnami ./data/rpm_data.txt bitnami@35.224.122.42:/opt/bitnami/apache/htdocs/data
    scp -i ~/.ssh/bitnami ./data/temp_data.txt bitnami@35.224.122.42:/opt/bitnami/apache/htdocs/data

    # Clean the cache files
    echo -n > ./data/gps_data.txt
    echo -n > ./data/rpm_data.txt
    echo -n > ./data/temp_data.txt
done
