#!/bin/bash

echo -n > ./log/log.txt

# Write any printouts to the log
exec 1>./log/log.txt
exec 2>./log/log.txt

echo "Welcome to the vehicle monitoring system of PUP vehicles"

# Manually updated field
# Specify the vehicle ID here. Each vehicle should have a unique ID
# It should be initialized before running the program
vid=demo

sudo pigpiod 2> /dev/null
echo -n > ./data/pid.txt

python3 pupgps.py $vid &
echo $! >> ./data/pid.txt
echo $!  # For testing purpose
echo "GPS sensor started successfully"

python3 temp.py $vid &
echo $! >> ./data/pid.txt
echo $!  # For testing purpose
echo "Temperature sensor started successfully"

python3 read_RPM.py $vid &
echo $! >> ./data/pid.txt
echo $!  # For testing purpose
echo "RPM sensor started successfully"

echo "All sensors started successfully! The monitoring has started..."

while true; do
    # Check if Raspberry Pi is connected to WiFi
    if [[ $(iwgetid) ]]; then
        echo "Internet is available. Start transporting data..."
    else
	      echo "Internet is not available. Continue collecting data and try uploading next time..."
	      sleep 60
	      continue
    fi

    # Upload data files to the cloud
    # In order to do so, the ssh key must be generated in the local machine
    scp -i ~/.ssh/bitnami ./data/gps_data.txt bitnami@35.224.122.42:/opt/bitnami/apache/htdocs/data
    scp -i ~/.ssh/bitnami ./data/rpm_data.txt bitnami@35.224.122.42:/opt/bitnami/apache/htdocs/data
    scp -i ~/.ssh/bitnami ./data/temp_data.txt bitnami@35.224.122.42:/opt/bitnami/apache/htdocs/data

    # Clean all cache files
    echo -n > ./data/gps_data.txt
    echo -n > ./data/rpm_data.txt
    echo -n > ./data/temp_data.txt

    # Upload GPS, RPM, and temperature data every 1 minute
    sleep 60
done
