#!/bin/bash

mkdir -p data
mkdir -p log

echo "Start vehicle monitoring system..."
./driver &
echo "Started successfully..."

read -p "Press enter to shut down the system..."
killall driver
python3 stop.py

echo "System has been shut down..."
exit 0
